remote_theme: pages-themes/minimal@v0.2.0
title: Friction Flatpak Repository
description: Official stable and devel builds for Friction.
show_downloads: false
logo: https://friction.graphics/assets/logo.svg
